# Generated by Django 3.0.6 on 2020-06-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'Responsábilidade'), ('1', 'Manutenção'), ('2', 'B.O')], max_length=255)),
                ('img', models.ImageField(upload_to='')),
                ('data', models.DateTimeField()),
                ('colab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prom.Colaborador')),
            ],
        ),
    ]
